---
# defaults file for wireguard_role

# Declare the VPN subnet
vpn_network: '10.203.200'

# Declare the VPN server port
vpn_port: '51820'

# Declare the number of clients
clients: 15

client_config_path: '~/wireguard_role/profiles'
