---
- name: Install iptables-persistent
  ansible.builtin.apt:
    name: iptables-persistent
    state: present

- name: Enable IPv4 traffic forwarding
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: yes
    state: present
    reload: yes

- name: Enable IPv4 forwarding continued
  ansible.builtin.command: echo 1 > /proc/sys/net/ipv4/ip_forward
  changed_when: false

# Set up firewall rules
- name: Track input chain
  ansible.builtin.iptables:
    chain: INPUT
    match: conntrack
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT

- name: Track forward chain
  ansible.builtin.iptables:
    chain: FORWARD
    match: conntrack
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT

- name: Allow incoming wireguard connections
  ansible.builtin.iptables:
    chain: INPUT
    protocol: udp
    match: udp
    destination_port: "{{ vpn_port }}"
    ctstate: NEW
    jump: ACCEPT

- name: Allow forwarding of packets that stay in the tunnel
  ansible.builtin.iptables:
    chain: FORWARD
    in_interface: wg0
    match: conntrack
    out_interface: wg0
    ctstate: NEW
    jump: ACCEPT

- name: Set up NAT
  ansible.builtin.iptables:
    table: nat
    chain: POSTROUTING
    source: "{{ vpn_network }}.0/24"
    out_interface: "{{ ansible_facts['default_ipv4']['interface'] }}"
    jump: MASQUERADE

- name: Set up iptables persistence
  ansible.builtin.shell: iptables-save > /etc/iptables/rules.v4
  changed_when: false
